/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddCharges.java
 *
 * Created on Jun 29, 2021, 11:02:02 PM
 */

package serviceportal;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author sgjohn
 */
public class AddCharges extends javax.swing.JFrame {

    /** Creates new form AddCharges */
    public AddCharges() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        complaints = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        charges = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        serviceid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(serviceportal.ServicePortalApp.class).getContext().getResourceMap(AddCharges.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel4.setBackground(resourceMap.getColor("jLabel4.background")); // NOI18N
        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        updatebtn.setText(resourceMap.getString("updatebtn.text")); // NOI18N
        updatebtn.setName("updatebtn"); // NOI18N
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        complaints.setName("complaints"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        charges.setText(resourceMap.getString("charges.text")); // NOI18N
        charges.setName("charges"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        serviceid.setText(resourceMap.getString("serviceid.text")); // NOI18N
        serviceid.setName("serviceid"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGap(106, 106, 106)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(charges, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(serviceid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(complaints, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updatebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(75, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {charges, complaints, serviceid, updatebtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(serviceid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(charges, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(complaints, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(87, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-616)/2, (screenSize.height-449)/2, 616, 449);
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        String amount = charges.getText();
        String comp = complaints.getSelectedItem().toString();
         DateFormat df = new SimpleDateFormat("dd-MMM-yy");
        DateFormat dt = new SimpleDateFormat("HH:mm");
         Calendar cal = Calendar.getInstance();
        String rdate = df.format(cal.getTime());
        String rtime = dt.format(cal.getTime());
        Connection con = DBConnection.getConnection();


        if(!this.deliveryStatus(serviceid.getText()))
        {
            JOptionPane.showMessageDialog(null,"Adding Charges not possible","Error",JOptionPane.ERROR_MESSAGE);
            this.dispose();
            return;
        }

        try
        {
           Statement st = con.createStatement();

           int j= st.executeUpdate("insert into extracharges values('"+serviceid.getText()+"','"+amount+"'" +
                   ",'"+rdate+"','"+rtime+"','"+comp+"','"+ServicePortalApp.getUsername()+"')");
           if(j==0)
           {
               JOptionPane.showMessageDialog(null,"Update Error","Error",JOptionPane.ERROR_MESSAGE);
              return;
           }
           else
           {
                JOptionPane.showMessageDialog(null,"successfully updated");
                this.dispose();
           }

        }
        catch(Exception  e)
        {
            e.printStackTrace();
        }






    }//GEN-LAST:event_updatebtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCharges().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField charges;
    private javax.swing.JComboBox complaints;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField serviceid;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables


public void setServiceId(String sid)
{
    serviceid.setText(sid);
    serviceid.setEnabled(false);
}

 public void loadCombo()
    {
        Connection connection=null;
        Statement statement= null;
        ResultSet rs= null;

        try
        {
           connection=DBConnection.getConnection();
           statement=connection.createStatement();
           rs=statement.executeQuery("select complaint_name from clist order by complaint_name asc");
           while(rs.next())
           {
               complaints.addItem(rs.getString("complaint_name"));
           }

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

 public int getCharges(String sid)
 {
     Connection con =DBConnection.getConnection();
     int amount=0;
     try
     {
         Statement st = con.createStatement();

        ResultSet rs =  st.executeQuery("select charges from extracharges where serviceid='"+sid+"'");

        while(rs.next())
        {
            amount=rs.getInt("charges");
        }
     }

     catch(Exception e)
     {
         e.printStackTrace();
     }
     return amount;
 }

public String getComplaint(String sid)
{
    Connection con =DBConnection.getConnection();
     String comp="";
     try
     {
         Statement st = con.createStatement();

        ResultSet rs =  st.executeQuery("select complaint from extracharges where serviceid='"+sid+"'");

        while(rs.next())
        {
            comp=rs.getString("Complaint");
        }
     }

     catch(Exception e)
     {
         e.printStackTrace();
     }
     return comp;

}

public Boolean checkServiceId(String sid)
{
    Boolean status=false;
    int count=0;
    Connection con =DBConnection.getConnection();
    try
     {
         Statement st = con.createStatement();

        ResultSet rs =  st.executeQuery("select charges from extracharges where serviceid='"+sid+"'");

        while(rs.next())
        {
           count++;
        }
     }

     catch(Exception e)
     {
         e.printStackTrace();
     }
    if(count!=0)
    {
        return false;
    }
    else
        return true;
}

public Boolean deliveryStatus(String sid)
{
  Connection con =DBConnection.getConnection();
  String dstatus="";
  String status="";
  try
     {
         Statement st = con.createStatement();

        ResultSet rs =  st.executeQuery("select status,delivery_status from status where receipt_no='"+sid+"'");

        while(rs.next())
        {
            status=rs.getString("status");
            dstatus=rs.getString("delivery_status");
        }
     }
  
     catch(Exception e)
     {
         e.printStackTrace();
     }
   if(dstatus.equals("Delivered") || status.equals("Failed") || status.equals("Cancelled"))
      return false;
   else
       return true;
}


}
