/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddUser.java
 *
 * Created on Aug 30, 2015, 12:01:02 AM
 */

package serviceportal;


import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sonytara
 */
public class AddUser extends javax.swing.JFrame {

    /** Creates new form AddUser */
    public AddUser() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwd1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        passwd2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        fullnameTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(serviceportal.ServicePortalApp.class).getContext().getResourceMap(AddUser.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 50, 130, 14);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(310, 50, 170, 20);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 100, 110, 14);

        passwd1.setText(resourceMap.getString("passwd1.text")); // NOI18N
        passwd1.setName("passwd1"); // NOI18N
        getContentPane().add(passwd1);
        passwd1.setBounds(310, 100, 170, 20);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 150, 100, 14);

        passwd2.setText(resourceMap.getString("passwd2.text")); // NOI18N
        passwd2.setName("passwd2"); // NOI18N
        getContentPane().add(passwd2);
        passwd2.setBounds(310, 150, 170, 20);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 200, 90, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TECHNICIAN", "RECEPTIONIST" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(310, 200, 170, 20);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 250, 80, 14);

        fullnameTxt.setText(resourceMap.getString("fullnameTxt.text")); // NOI18N
        fullnameTxt.setName("fullnameTxt"); // NOI18N
        getContentPane().add(fullnameTxt);
        fullnameTxt.setBounds(310, 250, 170, 20);

        addBtn.setText(resourceMap.getString("addBtn.text")); // NOI18N
        addBtn.setName("addBtn"); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn);
        addBtn.setBounds(140, 333, 90, 40);

        resetBtn.setText(resourceMap.getString("resetBtn.text")); // NOI18N
        resetBtn.setName("resetBtn"); // NOI18N
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn);
        resetBtn.setBounds(361, 333, 110, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-640)/2, (screenSize.height-480)/2, 640, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        Statement st = null;
        if(!passwd1.getText().equals(passwd2.getText()))
        {
            JOptionPane.showMessageDialog(null, "Password Mismatch","error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try
        {
            String sql="";
            con=DBConnection.getConnection();
            ResultSet rs=null;
            st=con.createStatement();

            if(jComboBox1.getSelectedItem().toString().equals("TECHNICIAN"))
            {
                rs=st.executeQuery("select userid from technician where userid='"+jTextField1.getText()+"'");
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null, "User already exist","ERROR",JOptionPane.ERROR_MESSAGE);
                 return;
            }
            }
             if(jComboBox1.getSelectedItem().toString().equals("RECEPTIONIST"))
             {
                 rs=st.executeQuery("select userid from users where userid='"+jTextField1.getText()+"'");
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null, "User already exist","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
             }
            if(jComboBox1.getSelectedItem().toString().equals("TECHNICIAN"))
            sql="insert into technician(USERID, PASSWD, FULL_NAME) values('"+jTextField1.getText()+"','"+passwd1.getText()+"'" +
                    ",'"+fullnameTxt.getText()+"') ";
            else if(jComboBox1.getSelectedItem().toString().equals("RECEPTIONIST"))
                sql="insert into users values('"+jTextField1.getText()+"','"+passwd1.getText()+"','"+fullnameTxt.getText()+"'" +
                        ",'RECEPTIONIST')";

            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "User Created");
            resetData();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        resetData();
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField fullnameTxt;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField passwd1;
    private javax.swing.JPasswordField passwd2;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables

    private void resetData() {
        jTextField1.setText("");
        passwd1.setText("");
        passwd2.setText("");
        fullnameTxt.setText("");
    }

}
