/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewComplaint.java
 *
 * Created on Aug 8, 2015, 1:36:39 AM
 */

package serviceportal;

import java.sql.*;
import java.text.*;
import java.util.*;
import javax.swing.*;


/**
 *
 * @author sgjohn
 */
public class NewComplaint extends javax.swing.JFrame {

    /** Creates new form NewComplaint */
    public NewComplaint() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createbtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contactno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneModel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        est_charges = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        advancetxt = new javax.swing.JTextField();
        mode = new javax.swing.JLabel();
        cashtype = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        emailaddr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        imeino = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(serviceportal.ServicePortalApp.class).getContext().getResourceMap(NewComplaint.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Form"); // NOI18N
        setResizable(false);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        createbtn.setText(resourceMap.getString("createbtn.text")); // NOI18N
        createbtn.setName("createbtn"); // NOI18N
        createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnActionPerformed(evt);
            }
        });

        resetbtn.setText(resourceMap.getString("resetbtn.text")); // NOI18N
        resetbtn.setName("resetbtn"); // NOI18N
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        cname.setText(resourceMap.getString("cname.text")); // NOI18N
        cname.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cname.setName("cname"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        contactno.setText(resourceMap.getString("contactno.text")); // NOI18N
        contactno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contactno.setName("contactno"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        phoneModel.setText(resourceMap.getString("phoneModel.text")); // NOI18N
        phoneModel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        phoneModel.setName("phoneModel"); // NOI18N
        phoneModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneModelActionPerformed(evt);
            }
        });

        jLabel5.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jComboBox1.setName("jComboBox1"); // NOI18N

        jLabel8.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        est_charges.setText(resourceMap.getString("est_charges.text")); // NOI18N
        est_charges.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        est_charges.setName("est_charges"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        advancetxt.setText(resourceMap.getString("advancetxt.text")); // NOI18N
        advancetxt.setName("advancetxt"); // NOI18N

        mode.setFont(resourceMap.getFont("mode.font")); // NOI18N
        mode.setText(resourceMap.getString("mode.text")); // NOI18N
        mode.setName("mode"); // NOI18N

        cashtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Direct Cash", "UPI Payment" }));
        cashtype.setName("cashtype"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(contactno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneModel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(96, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(mode)
                                .addGap(56, 56, 56)
                                .addComponent(cashtype, 0, 306, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(advancetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(est_charges, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, 300, Short.MAX_VALUE))))
                        .addGap(96, 96, 96))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneModel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(est_charges, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(advancetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mode)
                    .addComponent(cashtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setName("jPanel2"); // NOI18N

        jCheckBox1.setSelected(true);
        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText(resourceMap.getString("jCheckBox2.text")); // NOI18N
        jCheckBox2.setName("jCheckBox2"); // NOI18N

        jCheckBox3.setText(resourceMap.getString("jCheckBox3.text")); // NOI18N
        jCheckBox3.setName("jCheckBox3"); // NOI18N

        jCheckBox4.setText(resourceMap.getString("jCheckBox4.text")); // NOI18N
        jCheckBox4.setName("jCheckBox4"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        emailaddr.setText(resourceMap.getString("emailaddr.text")); // NOI18N
        emailaddr.setName("emailaddr"); // NOI18N

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        imeino.setText(resourceMap.getString("imeino.text")); // NOI18N
        imeino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imeino.setName("imeino"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(imeino, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emailaddr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imeino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(448, 448, 448)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addComponent(createbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneModelActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void createbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnActionPerformed
        // TODO add your handling code here:
        
        DateFormat df = new SimpleDateFormat("dd-MMM-yy");
        DateFormat dt = new SimpleDateFormat("HH:mm");
        Calendar cal = Calendar.getInstance();
        String cname1 = cname.getText();
        String contact_no = contactno.getText();
        String phone_model = phoneModel.getText();
        String compl_name = jComboBox1.getSelectedItem().toString();
        String recvd_accr = "";
        String recvd_by = ServicePortalApp.getUsername();
        String receipt_no="";
        String recvd_date = df.format(cal.getTime());
        String est_charges1 = est_charges.getText();
        String recvd_time = dt.format(cal.getTime());
        String imei_no = imeino.getText();
        String email = emailaddr.getText();
        String sql="";
        int cashIndex = cashtype.getSelectedIndex();
        String cashMode = cashIndex==0 ? "Direct Cash" : "UPI";



        if(jCheckBox1.isSelected())
        {
            recvd_accr=jCheckBox1.getText();
        }
        if(advancetxt.getText().equals(("")))
        {
            advancetxt.setText("0");
        }

        if(jCheckBox2.isSelected())
        {
            recvd_accr = recvd_accr + ","+ jCheckBox2.getText();
        }
        if(jCheckBox3.isSelected())
        {
            recvd_accr = recvd_accr + ","+ jCheckBox3.getText();
        }
        if(jCheckBox4.isSelected())
        {
            recvd_accr = recvd_accr + ","+ jCheckBox4.getText();
        }
         String i= StringTrim.trim(new StringBuilder(recvd_accr), ',');
       recvd_accr=i;
       

       if(!contact_no.matches("\\d{10}") && !contact_no.equals(""))
       {
           JOptionPane.showMessageDialog(null, "invalid contact no");
                   return;
       }
       else if(!imei_no.matches("\\d{15}") && !imei_no.equals(""))
       {
           JOptionPane.showMessageDialog(null, "invalid imei no");
                   return;
       }
       else if(!est_charges1.matches("[0-9]+") || est_charges1.length()>5 || est_charges1.equals(""))
       {
           JOptionPane.showMessageDialog(null, "invalid amount");
                   return;
       }
       else if(cname1.equals("") || phone_model.equals("") || compl_name.equals(""))
       {
           JOptionPane.showMessageDialog(null, "enter input text");
                   return;
       }

       boolean updateLast=false;
       boolean print=true;


       try
        {
            Statement sa = con.createStatement();
            ResultSet rs = sa.executeQuery("select LAST,DAYS_NO from billpart");
            String adv = advancetxt.getText();
            int bal = Integer.parseInt(est_charges1)-Integer.parseInt(adv);
            while(rs.next())
            {
                last_part=Integer.parseInt(rs.getString(1));
                days_no=Integer.parseInt(rs.getString(2));
            }
            receipt_no=generateServiceID();

             sql="insert into complaint(CNAME, CONTACT_NO, PHONE_MODEL, COMPLAINT_NAME, RECVD_ACCR, RECVD_BY, RECEIPT_NO, RECVD_DATE, EST_CHARGS, RECVD_TIME,IMEI_NO,email,advance,balance) " +
                    "values('"+cname1+"',"+contact_no+",'"+phone_model+"','"+compl_name+"','"+recvd_accr+"','"+recvd_by+"','"
                    +receipt_no+"','"+recvd_date+"',"+est_charges1+",'"+recvd_time+"',"+ imei_no+",'"+email+"',"+adv+","+bal+")";


       if(contactno.getText().equals("") && !imeino.getText().equals("")&& emailaddr.getText().equals(""))
       {
           sql="insert into complaint(CNAME, PHONE_MODEL, COMPLAINT_NAME, RECVD_ACCR, RECVD_BY, RECEIPT_NO, RECVD_DATE, EST_CHARGS, RECVD_TIME,IMEI_NO,advance,balance) " +
                    "values('"+cname1+"','"+phone_model+"','"+compl_name+"','"+recvd_accr+"','"+recvd_by+"','"
                    +receipt_no+"','"+recvd_date+"',"+est_charges1+",'"+recvd_time+"',"+ imei_no+","+adv+","+bal+")";
       }
       if(!contactno.getText().equals("") && imeino.getText().equals("") && emailaddr.getText().equals(""))
       {
           sql="insert into complaint(CNAME, CONTACT_NO, PHONE_MODEL, COMPLAINT_NAME, RECVD_ACCR, RECVD_BY, RECEIPT_NO, RECVD_DATE, EST_CHARGS, RECVD_TIME,advance,balance) " +
                    "values('"+cname1+"',"+contact_no+",'"+phone_model+"','"+compl_name+"','"+recvd_accr+"','"+recvd_by+"','"
                    +receipt_no+"','"+recvd_date+"',"+est_charges1+",'"+recvd_time+"',"+adv+","+bal+")";
       }
       if(contactno.getText().equals("") && imeino.getText().equals("") && emailaddr.getText().equals(""))
       {
           sql="insert into complaint(CNAME, PHONE_MODEL, COMPLAINT_NAME, RECVD_ACCR, RECVD_BY, RECEIPT_NO, RECVD_DATE, EST_CHARGS, RECVD_TIME,advance,balance) " +
                    "values('"+cname1+"','"+phone_model+"','"+compl_name+"','"+recvd_accr+"','"+recvd_by+"','"
                    +receipt_no+"','"+recvd_date+"',"+est_charges1+",'"+recvd_time+"',"+adv+","+bal+")";
       }
                    
        
	     if(contactno.getText().equals("") && !imeino.getText().equals("")&& !emailaddr.getText().equals("")) 
       {
           sql="insert into complaint(CNAME, PHONE_MODEL, COMPLAINT_NAME, RECVD_ACCR, RECVD_BY, RECEIPT_NO, RECVD_DATE, EST_CHARGS, RECVD_TIME,IMEI_NO,email,advance,balance) " +
                    "values('"+cname1+"','"+phone_model+"','"+compl_name+"','"+recvd_accr+"','"+recvd_by+"','"
                    +receipt_no+"','"+recvd_date+"',"+est_charges1+",'"+recvd_time+"',"+ imei_no+",'"+email+"',"+adv+","+bal+")";
       }
       if(!contactno.getText().equals("") && imeino.getText().equals("") && !emailaddr.getText().equals("")) 
       {
           sql="insert into complaint(CNAME, CONTACT_NO, PHONE_MODEL, COMPLAINT_NAME, RECVD_ACCR, RECVD_BY, RECEIPT_NO, RECVD_DATE, EST_CHARGS, RECVD_TIME,email,advance,balance) " +
                    "values('"+cname1+"',"+contact_no+",'"+phone_model+"','"+compl_name+"','"+recvd_accr+"','"+recvd_by+"','"
                    +receipt_no+"','"+recvd_date+"',"+est_charges1+",'"+recvd_time+"','"+email+"',"+adv+","+bal+")";
       }
       if(contactno.getText().equals("") && imeino.getText().equals("") && !emailaddr.getText().equals("")) 
       {
           sql="insert into complaint(CNAME, PHONE_MODEL, COMPLAINT_NAME, RECVD_ACCR, RECVD_BY, RECEIPT_NO, RECVD_DATE, EST_CHARGS, RECVD_TIME,email,advance,balance) " +
                    "values('"+cname1+"','"+phone_model+"','"+compl_name+"','"+recvd_accr+"','"+recvd_by+"','"
                    +receipt_no+"','"+recvd_date+"',"+est_charges1+",'"+recvd_time+"','"+email+"',"+adv+","+bal+")";
       }
	   
	   
	   
	     if(!contactno.getText().equals("") && !imeino.getText().equals("") && emailaddr.getText().equals("")) 
       {
             sql="insert into complaint(CNAME, CONTACT_NO, PHONE_MODEL, COMPLAINT_NAME, RECVD_ACCR, RECVD_BY, RECEIPT_NO, RECVD_DATE, EST_CHARGS, RECVD_TIME,IMEI_NO,advance,balance) " +
                    "values('"+cname1+"',"+contact_no+",'"+phone_model+"','"+compl_name+"','"+recvd_accr+"','"+recvd_by+"','"
                    +receipt_no+"','"+recvd_date+"',"+est_charges1+",'"+recvd_time+"',"+ imei_no+","+adv+","+bal+")";

       }



             sa.executeUpdate("update billpart set last='"+last_part+"',days_no='"+days_no+
                    "' where ex='PASS'");
           // String a = "insert into complaint(CNAME, CONTACT_NO, PHONE_MODEL, COMPLAINT_NAME, RECVD_ACCR, RECVD_BY, RECEIPT_NO, RECVD_DATE, EST_CHARGS, RECVD_TIME)" +
            //        " values('"+cname1+"',"+contact_no+",'"+phone_model+"','"+compl_name+"','"+recvd_accr+"','"+recvd_by+"','"
            //        +receipt_no+"','"+recvd_date+"',"+est_charges1+",'"+recvd_time+"',"+ imei_no+")";
            
           updateLast=true;
            int j= sa.executeUpdate(sql);



        sa.executeUpdate("insert into status values('"+receipt_no+"','"+compl_name+"','New','"+recvd_date+"','NO')");
        this.setVisible(false);
       if(Integer.parseInt(adv)>0)
       {
         sa.executeUpdate("insert into payments values('"+receipt_no+"',"+adv+",'advance','"+recvd_date+"','"+recvd_time+"','"+recvd_by+"','"+cashMode+"')");
       }

       
        if(j!=0)
        {
             JOptionPane.showMessageDialog(null,"New Complaint registered suuccessfully with service id:"+receipt_no);
             

        }
        else if(j==0)
        {
                     
            last_part=last_part-1;
            
            sa.executeUpdate("update billpart set last="+last_part+",days_no="+days_no+
                    "where ex='PASS'");
        }
            
        try
        {
             String msg="New Complaint:"+receipt_no;
             msg=msg+"\nCustomer Name: "+cname1;
             msg=msg+"\nMobile Number: "+contact_no;
             msg=msg+"\nComplaint: "+compl_name;
             msg=msg+"\nEst Charges: "+est_charges1;
             msg=msg+"\nPhone Model:"+phone_model;
             msg=msg+"\nCash Mode:"+cashMode;
             msg=msg+"\n Advance amount: "+adv;
             Mailer.send("digitalcarekvl@gmail.com","a_123456","digital.eck@gmail.com","Digital Electronics",msg);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

        this.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Database Error", 0);
            if(updateLast)
            {
               resetLast();
            }
            print=false;
            this.dispose();
        }

      if(!print)
          return;
       JOptionPane.showMessageDialog(null,"Please Wait while bill is generating");;



       try{


            HashMap parameterMap = new HashMap();
            parameterMap.put("billno",receipt_no);
            printClass prc = new printClass(parameterMap, con);
             prc.setreportName("digital.jasper");
            prc.callReport();
          }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
       

    }//GEN-LAST:event_createbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
         cname.setText(null);
         contactno.setText(null);
         phoneModel.setText(null);
         est_charges.setText(null);
         imeino.setText(null);
    }//GEN-LAST:event_resetbtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewComplaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advancetxt;
    private javax.swing.JComboBox cashtype;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField contactno;
    private javax.swing.JButton createbtn;
    private javax.swing.JTextField emailaddr;
    private javax.swing.JTextField est_charges;
    private javax.swing.JTextField imeino;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mode;
    private javax.swing.JTextField phoneModel;
    private javax.swing.JButton resetbtn;
    // End of variables declaration//GEN-END:variables

    private Integer last_part;
    private Integer days_no;
    Connection con = DBConnection.getConnection();
    private String generateServiceID() {



        DateFormat df = new SimpleDateFormat("yyDD");
        Calendar cal = Calendar.getInstance();
        DateFormat d1 = new SimpleDateFormat("DD");
        DateFormat d2 = new SimpleDateFormat("yy");
        int new_days = Integer.parseInt(d1.format(cal.getTime()));
        String dayString = d1.format(cal.getTime());

        if(new_days>days_no)
            last_part=1;
        else if(last_part==999)
            last_part=1;
       else if(new_days<days_no)
            last_part=1;
       else
            last_part=last_part+1;
        
        String s = df.format(cal.getTime());
        StringBuffer str = new StringBuffer(dayString);
        if(str.length()<3)
        {
            int i=0;
            while(str.length()!=3)
            {
                
                str.insert(i, 0);
                i++;
                
            }

            s=d2.format(cal.getTime());
            s=s+str.toString();
        }

        s = s+ String.format("%03d", last_part);
        days_no=new_days;


        ServicePortalView.setServiceID(s);
        return s;
    }

    public void loadCombo()
    {
        Connection connection=null;
        Statement statement= null;
        ResultSet rs= null;

        try
        {
           connection=DBConnection.getConnection();
           statement=connection.createStatement();
           rs=statement.executeQuery("select complaint_name from clist  order by complaint_name asc");
           while(rs.next())
           {
               jComboBox1.addItem(rs.getString("complaint_name"));
           }

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    private void resetLast() {
        try
        {
            
                last_part=last_part-1;
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            st.executeUpdate("update billpart set last="+last_part+",days_no="+days_no+
                    "where ex='PASS'");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
}
