/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResetPasswd.java
 *
 * Created on Aug 31, 2015, 10:26:09 AM
 */

package serviceportal;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author sonytara
 */
public class ResetPasswd extends javax.swing.JFrame {

    /** Creates new form ResetPasswd */
    public ResetPasswd() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(serviceportal.ServicePortalApp.class).getContext().getResourceMap(ResetPasswd.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 90, 64, 27);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 90, 230, 20);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 140, 110, 14);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 180, 70, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TECHNICIAN", "RECEPTIONIST" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(300, 180, 230, 20);

        jPasswordField1.setText(resourceMap.getString("jPasswordField1.text")); // NOI18N
        jPasswordField1.setName("jPasswordField1"); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(300, 130, 230, 20);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 280, 130, 50);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-640)/2, (screenSize.height-480)/2, 640, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection connection=null;
        Statement st = null;
        try
        {
          connection=DBConnection.getConnection();
          st=connection.createStatement();
          int i=0;
          if(jComboBox1.getSelectedItem().toString().equals("TECHNICIAN"))
          {
             i= st.executeUpdate("update technician set passwd='"+jPasswordField1.getText()+"' where userid='"+jTextField1.getText()+"'");
          }
          if(jComboBox1.getSelectedItem().toString().equals("RECEPTIONIST"))
          {
              i= st.executeUpdate("update users set passwd='"+jPasswordField1.getText()+"' where userid='"+jTextField1.getText()+"'");
          }

            if(i==0)
           {
              JOptionPane.showMessageDialog(null, "Userid does not exist","Error",JOptionPane.ERROR_MESSAGE);
              return;
           }
              JOptionPane.showMessageDialog(null, "Password Reset Successfull");
         

        }
        catch(Exception e)
        {

            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPasswd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
