/*
 * ServicePortalView.java
 */

package serviceportal;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * The application's main frame.
 */
public class ServicePortalView extends FrameView {

    public ServicePortalView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = ServicePortalApp.getApplication().getMainFrame();
            aboutBox = new ServicePortalAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        ServicePortalApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        viewBtn = new javax.swing.JButton();
        newbTN = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        updateBtn = new javax.swing.JButton();
        statbttn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu serviceMenu = new javax.swing.JMenu();
        NewComplaint = new javax.swing.JMenuItem();
        SearchMenu = new javax.swing.JMenuItem();
        printMenu = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        deliveryMenu = new javax.swing.JMenu();
        delHandset = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        adminMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        statusMenu = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        newSetsMenu = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        techReportsMenu = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        profileMenu = new javax.swing.JMenu();
        changePasswd = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(serviceportal.ServicePortalApp.class).getContext().getResourceMap(ServicePortalView.class);
        jDesktopPane1.setBackground(resourceMap.getColor("jDesktopPane1.background")); // NOI18N
        jDesktopPane1.setForeground(resourceMap.getColor("jDesktopPane1.foreground")); // NOI18N
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1024, 750));
        jDesktopPane1.setName("jDesktopPane1"); // NOI18N
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setBounds(400, 260, 230, 30);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setBackground(resourceMap.getColor("jLabel1.background")); // NOI18N
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setBounds(220, 190, 590, 50);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        viewBtn.setIcon(resourceMap.getIcon("viewBtn.icon")); // NOI18N
        viewBtn.setText(resourceMap.getString("viewBtn.text")); // NOI18N
        viewBtn.setToolTipText(resourceMap.getString("viewBtn.toolTipText")); // NOI18N
        viewBtn.setFocusable(false);
        viewBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewBtn.setName("viewBtn"); // NOI18N
        viewBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(viewBtn);

        newbTN.setIcon(resourceMap.getIcon("newbTN.icon")); // NOI18N
        newbTN.setText(resourceMap.getString("newbTN.text")); // NOI18N
        newbTN.setToolTipText(resourceMap.getString("newbTN.toolTipText")); // NOI18N
        newbTN.setFocusable(false);
        newbTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newbTN.setName("newbTN"); // NOI18N
        newbTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newbTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbTNActionPerformed(evt);
            }
        });
        jToolBar1.add(newbTN);

        SearchBtn.setIcon(resourceMap.getIcon("SearchBtn.icon")); // NOI18N
        SearchBtn.setText(resourceMap.getString("SearchBtn.text")); // NOI18N
        SearchBtn.setToolTipText(resourceMap.getString("SearchBtn.toolTipText")); // NOI18N
        SearchBtn.setFocusable(false);
        SearchBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchBtn.setName("SearchBtn"); // NOI18N
        SearchBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(SearchBtn);

        printBtn.setIcon(resourceMap.getIcon("printBtn.icon")); // NOI18N
        printBtn.setText(resourceMap.getString("printBtn.text")); // NOI18N
        printBtn.setToolTipText(resourceMap.getString("printBtn.toolTipText")); // NOI18N
        printBtn.setFocusable(false);
        printBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        printBtn.setName("printBtn"); // NOI18N
        printBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(printBtn);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jToolBar1.add(jSeparator1);

        updateBtn.setIcon(resourceMap.getIcon("updateBtn.icon")); // NOI18N
        updateBtn.setText(resourceMap.getString("updateBtn.text")); // NOI18N
        updateBtn.setToolTipText(resourceMap.getString("updateBtn.toolTipText")); // NOI18N
        updateBtn.setFocusable(false);
        updateBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateBtn.setName("updateBtn"); // NOI18N
        updateBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(updateBtn);

        statbttn.setIcon(resourceMap.getIcon("statbttn.icon")); // NOI18N
        statbttn.setText(resourceMap.getString("statbttn.text")); // NOI18N
        statbttn.setToolTipText(resourceMap.getString("statbttn.toolTipText")); // NOI18N
        statbttn.setFocusable(false);
        statbttn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        statbttn.setName("statbttn"); // NOI18N
        statbttn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        statbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statbttnActionPerformed(evt);
            }
        });
        jToolBar1.add(statbttn);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jToolBar1.add(jSeparator2);

        jToolBar1.setBounds(0, 0, 1260, 30);
        jDesktopPane1.add(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuBar.setName("menuBar"); // NOI18N

        serviceMenu.setText(resourceMap.getString("serviceMenu.text")); // NOI18N
        serviceMenu.setName("serviceMenu"); // NOI18N
        serviceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceMenuActionPerformed(evt);
            }
        });

        NewComplaint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NewComplaint.setIcon(resourceMap.getIcon("NewComplaint.icon")); // NOI18N
        NewComplaint.setText(resourceMap.getString("NewComplaint.text")); // NOI18N
        NewComplaint.setName("NewComplaint"); // NOI18N
        NewComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewComplaintActionPerformed(evt);
            }
        });
        serviceMenu.add(NewComplaint);

        SearchMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SearchMenu.setIcon(resourceMap.getIcon("SearchMenu.icon")); // NOI18N
        SearchMenu.setText(resourceMap.getString("SearchMenu.text")); // NOI18N
        SearchMenu.setName("SearchMenu"); // NOI18N
        SearchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMenuActionPerformed(evt);
            }
        });
        serviceMenu.add(SearchMenu);

        printMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        printMenu.setIcon(resourceMap.getIcon("printMenu.icon")); // NOI18N
        printMenu.setText(resourceMap.getString("printMenu.text")); // NOI18N
        printMenu.setName("printMenu"); // NOI18N
        printMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printMenuActionPerformed(evt);
            }
        });
        serviceMenu.add(printMenu);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(serviceportal.ServicePortalApp.class).getContext().getActionMap(ServicePortalView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setIcon(resourceMap.getIcon("exitMenuItem.icon")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        serviceMenu.add(exitMenuItem);

        menuBar.add(serviceMenu);

        deliveryMenu.setText(resourceMap.getString("deliveryMenu.text")); // NOI18N
        deliveryMenu.setName("deliveryMenu"); // NOI18N
        deliveryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryMenuActionPerformed(evt);
            }
        });

        delHandset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        delHandset.setIcon(resourceMap.getIcon("delHandset.icon")); // NOI18N
        delHandset.setText(resourceMap.getString("delHandset.text")); // NOI18N
        delHandset.setName("delHandset"); // NOI18N
        delHandset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delHandsetActionPerformed(evt);
            }
        });
        deliveryMenu.add(delHandset);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(resourceMap.getIcon("jMenuItem1.icon")); // NOI18N
        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        deliveryMenu.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(resourceMap.getIcon("jMenuItem2.icon")); // NOI18N
        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        deliveryMenu.add(jMenuItem2);

        menuBar.add(deliveryMenu);

        adminMenu.setText(resourceMap.getString("adminMenu.text")); // NOI18N
        adminMenu.setName("adminMenu"); // NOI18N
        adminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminMenuActionPerformed(evt);
            }
        });

        jMenuItem6.setIcon(resourceMap.getIcon("jMenuItem6.icon")); // NOI18N
        jMenuItem6.setText(resourceMap.getString("jMenuItem6.text")); // NOI18N
        jMenuItem6.setName("jMenuItem6"); // NOI18N
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        adminMenu.add(jMenuItem6);

        jMenuItem7.setIcon(resourceMap.getIcon("jMenuItem7.icon")); // NOI18N
        jMenuItem7.setText(resourceMap.getString("jMenuItem7.text")); // NOI18N
        jMenuItem7.setName("jMenuItem7"); // NOI18N
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        adminMenu.add(jMenuItem7);

        jMenuItem9.setIcon(resourceMap.getIcon("jMenuItem9.icon")); // NOI18N
        jMenuItem9.setText(resourceMap.getString("jMenuItem9.text")); // NOI18N
        jMenuItem9.setName("jMenuItem9"); // NOI18N
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        adminMenu.add(jMenuItem9);

        jMenuItem8.setIcon(resourceMap.getIcon("jMenuItem8.icon")); // NOI18N
        jMenuItem8.setText(resourceMap.getString("jMenuItem8.text")); // NOI18N
        jMenuItem8.setName("jMenuItem8"); // NOI18N
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        adminMenu.add(jMenuItem8);

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        jMenuItem10.setText(resourceMap.getString("jMenuItem10.text")); // NOI18N
        jMenuItem10.setName("jMenuItem10"); // NOI18N
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem12.setText(resourceMap.getString("jMenuItem12.text")); // NOI18N
        jMenuItem12.setName("jMenuItem12"); // NOI18N
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        adminMenu.add(jMenu1);

        menuBar.add(adminMenu);
        String g = ServicePortalApp.getUsername();
        if(g.equals("admin"))
        adminMenu.setEnabled(true);
        else
        adminMenu.setEnabled(false);

        statusMenu.setText(resourceMap.getString("statusMenu.text")); // NOI18N
        statusMenu.setName("statusMenu"); // NOI18N

        jMenuItem21.setText(resourceMap.getString("jMenuItem21.text")); // NOI18N
        jMenuItem21.setName("jMenuItem21"); // NOI18N
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        statusMenu.add(jMenuItem21);

        newSetsMenu.setIcon(resourceMap.getIcon("newSetsMenu.icon")); // NOI18N
        newSetsMenu.setText(resourceMap.getString("newSetsMenu.text")); // NOI18N
        newSetsMenu.setName("newSetsMenu"); // NOI18N
        newSetsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSetsMenuActionPerformed(evt);
            }
        });
        statusMenu.add(newSetsMenu);

        jMenuItem3.setIcon(resourceMap.getIcon("jMenuItem3.icon")); // NOI18N
        jMenuItem3.setText(resourceMap.getString("jMenuItem3.text")); // NOI18N
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        statusMenu.add(jMenuItem3);

        jMenuItem4.setIcon(resourceMap.getIcon("jMenuItem4.icon")); // NOI18N
        jMenuItem4.setText(resourceMap.getString("jMenuItem4.text")); // NOI18N
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        statusMenu.add(jMenuItem4);

        jMenuItem5.setIcon(resourceMap.getIcon("jMenuItem5.icon")); // NOI18N
        jMenuItem5.setText(resourceMap.getString("jMenuItem5.text")); // NOI18N
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        statusMenu.add(jMenuItem5);

        jMenuItem18.setText(resourceMap.getString("jMenuItem18.text")); // NOI18N
        jMenuItem18.setName("jMenuItem18"); // NOI18N
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        statusMenu.add(jMenuItem18);

        techReportsMenu.setText(resourceMap.getString("techReportsMenu.text")); // NOI18N
        techReportsMenu.setName("techReportsMenu"); // NOI18N

        jMenuItem19.setText(resourceMap.getString("jMenuItem19.text")); // NOI18N
        jMenuItem19.setName("jMenuItem19"); // NOI18N
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        techReportsMenu.add(jMenuItem19);

        jMenuItem13.setText(resourceMap.getString("jMenuItem13.text")); // NOI18N
        jMenuItem13.setName("jMenuItem13"); // NOI18N
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        techReportsMenu.add(jMenuItem13);

        jMenuItem11.setText(resourceMap.getString("jMenuItem11.text")); // NOI18N
        jMenuItem11.setName("jMenuItem11"); // NOI18N
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        techReportsMenu.add(jMenuItem11);

        jMenuItem14.setText(resourceMap.getString("jMenuItem14.text")); // NOI18N
        jMenuItem14.setName("jMenuItem14"); // NOI18N
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        techReportsMenu.add(jMenuItem14);

        jMenuItem15.setText(resourceMap.getString("jMenuItem15.text")); // NOI18N
        jMenuItem15.setName("jMenuItem15"); // NOI18N
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        techReportsMenu.add(jMenuItem15);

        jMenuItem16.setText(resourceMap.getString("jMenuItem16.text")); // NOI18N
        jMenuItem16.setName("jMenuItem16"); // NOI18N
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        techReportsMenu.add(jMenuItem16);

        jMenuItem17.setText(resourceMap.getString("jMenuItem17.text")); // NOI18N
        jMenuItem17.setName("jMenuItem17"); // NOI18N
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        techReportsMenu.add(jMenuItem17);

        jMenuItem20.setText(resourceMap.getString("jMenuItem20.text")); // NOI18N
        jMenuItem20.setName("jMenuItem20"); // NOI18N
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        techReportsMenu.add(jMenuItem20);

        statusMenu.add(techReportsMenu);

        menuBar.add(statusMenu);

        profileMenu.setText(resourceMap.getString("profileMenu.text")); // NOI18N
        profileMenu.setName("profileMenu"); // NOI18N

        changePasswd.setIcon(resourceMap.getIcon("changePasswd.icon")); // NOI18N
        changePasswd.setText(resourceMap.getString("changePasswd.text")); // NOI18N
        changePasswd.setName("changePasswd"); // NOI18N
        changePasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswdActionPerformed(evt);
            }
        });
        profileMenu.add(changePasswd);

        menuBar.add(profileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N
        helpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuActionPerformed(evt);
            }
        });

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1110, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void NewComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewComplaintActionPerformed
        // TODO add your handling code here:
      NewComplaint n = new NewComplaint();
      n.loadCombo();
      n.setVisible(true);

      
    }//GEN-LAST:event_NewComplaintActionPerformed

    private void serviceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceMenuActionPerformed

    private void printMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printMenuActionPerformed
        // TODO add your handling code here:
      Connection connctieon;
     /*   if(ServiceID==null)
       {
           JOptionPane.showMessageDialog(null,"No New Complaints available");
           
       } */
        ServiceID=JOptionPane.showInputDialog("Enter Service Id:");
        if(ServiceID.equals(""))
            return;
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            connctieon=DriverManager.getConnection("jdbc:oracle:thin:digital/digital@//localhost:1521/XE");
            Statement stmt = connctieon.createStatement();
            HashMap parameterMap = new HashMap();
            parameterMap.put("billno",ServiceID);
            printClass prc = new printClass(parameterMap, connctieon);
             prc.setreportName("digital.jasper");
            prc.callReport();
          }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_printMenuActionPerformed

    private void SearchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMenuActionPerformed
        // TODO add your handling code here:
        SearchComplaint s = new SearchComplaint();
        s.deleteVisible(false);
        s.setbutton();
        s.setVisible(true);
    }//GEN-LAST:event_SearchMenuActionPerformed

    private void delHandsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delHandsetActionPerformed
        // TODO add your handling code here:
        DeliverHandset.setServiceID("");
        DeliverHandset.delivery();

    }//GEN-LAST:event_delHandsetActionPerformed

    private void deliveryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryMenuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_deliveryMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String sid=JOptionPane.showInputDialog("Enter Service Id");
        Connection con = DBConnection.getConnection();
       Statement st = null;
       DateFormat df = new SimpleDateFormat("dd-MMM-yy hh:mm");
       DateFormat dt = new SimpleDateFormat("HH:mm");
       Calendar calendar= Calendar.getInstance();

       try
       {
           st=con.createStatement();
            ResultSet rs = st.executeQuery("select * from delivery where receipt_no='"+sid+"'");

           if(!rs.next())
           {
             JOptionPane.showMessageDialog(null,"This Handset not delivered yet ","Error",JOptionPane.ERROR_MESSAGE);
             return;
           }
           st.executeUpdate("insert into cancelled values('"+sid+"','Delivery Cancelled',to_date('"+df.format(calendar.getTime())+"','DD-MON-YY HH:MI'),'"+dt.format(calendar.getTime())+"','"+ServicePortalApp.getUsername()+"')");
           st.executeUpdate("update status set delivery_status='Returned' where receipt_no like '%"+sid+"%'");
           JOptionPane.showMessageDialog(null,"Delivery Record removed");
       }
       catch(Exception e)
       {
           
           e.printStackTrace();
       }
    JOptionPane.showMessageDialog(null,"Please wait while generating print report");
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection connctieon = DriverManager.getConnection("jdbc:oracle:thin:digital/digital@//localhost:1521/XE");
            Statement stmt = connctieon.createStatement();
            HashMap parameterMap = new HashMap();
            parameterMap.put("billno",sid);
            printClass prc = new printClass(parameterMap, connctieon);
             prc.setreportName("cancel.jasper");
            prc.callReport();
          }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DeliveryReports dr = new DeliveryReports();
        dr.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void helpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMenuActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        AddUser userAdd = new AddUser();
        userAdd.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void adminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminMenuActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_adminMenuActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        DeleteUser deleteUser = new DeleteUser();
        deleteUser.setVisible(true);

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        SearchComplaint s1 = new SearchComplaint();
        s1.deleteVisible(true);
        s1.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void newSetsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSetsMenuActionPerformed
        // TODO add your handling code here:
        StatusReport statusReport = new StatusReport();
        statusReport.loadTable("new");
        statusReport.setVisible(true);

    }//GEN-LAST:event_newSetsMenuActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         StatusReport statusReport = new StatusReport();
        statusReport.loadTable("pending");
        statusReport.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         StatusReport statusReport = new StatusReport();
        statusReport.loadTable("completed");
        statusReport.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         StatusReport statusReport = new StatusReport();
        statusReport.loadTable("failed");
        statusReport.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        String sid=JOptionPane.showInputDialog("Enter Service ID");
      if(sid==null)
          return;
        if(!sid.equals(""))
       {
        ViewReport viewReport = new ViewReport();
        viewReport.setDetails(sid);
        viewReport.setVisible(true);
       }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void newbTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbTNActionPerformed
        // TODO add your handling code here:
        NewComplaint newC = new NewComplaint();
        newC.loadCombo();
        newC.setVisible(true);
    }//GEN-LAST:event_newbTNActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        SearchComplaint search = new SearchComplaint();
        search.deleteVisible(false);
        search.setVisible(true);
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:

        ServiceID=JOptionPane.showInputDialog("Enter Service Id:");
        if(ServiceID==null)
            return;
        if(ServiceID.equals(""))
            return;
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection connctieon = DriverManager.getConnection("jdbc:oracle:thin:digital/digital@//localhost:1521/XE");
            Statement stmt = connctieon.createStatement();
            HashMap parameterMap = new HashMap();
            parameterMap.put("billno",ServiceID);
            printClass prc = new printClass(parameterMap, connctieon);
             prc.setreportName("digital.jasper");
            prc.callReport();
          }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_printBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
         if(!ServicePortalApp.getUsername().equals("admin"))
       {
           JOptionPane.showMessageDialog(null, "Access Denied","Error",JOptionPane.ERROR_MESSAGE);
           return;
       }
        
         String sid="";
         sid=JOptionPane.showInputDialog("Enter Service ID");
        if(sid==null)
            return;

         if(!sid.equals("") )
        {
        UpdateComplaint updateComplaint = new UpdateComplaint();
        updateComplaint.loadCombo();
        int i=updateComplaint.setServiceID(sid);
        if(i!=-1)
        updateComplaint.setVisible(true);
        else
            updateComplaint.dispose();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void statbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statbttnActionPerformed
        // TODO add your handling code here:
       String sid="";
         sid= JOptionPane.showInputDialog("Enter Service ID");
       if(sid==null)
           return;
         if(!sid.equals(""))
        {


        UpdateStatus update = new UpdateStatus();
        int i=update.setServiceID(sid);
        if(i!=-1)
        update.setVisible(true);
        else
            update.dispose();
        }

    }//GEN-LAST:event_statbttnActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        ResetPasswd resetPasswd = new ResetPasswd();
        resetPasswd.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void changePasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswdActionPerformed
        // TODO add your handling code here:
        ChangePasswd cp = new ChangePasswd();
        cp.setVisible(true);
    }//GEN-LAST:event_changePasswdActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        AddComp ac = new AddComp();
        ac.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        DelCom d = new DelCom();
        d.loadData();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        TechnicianReports tr= new TechnicianReports();
        tr.setStatusMode("New");
        tr.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        TechnicianReports tr= new TechnicianReports();
        tr.setStatusMode("NOID");
        tr.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
         TechnicianReports tr= new TechnicianReports();
        tr.setStatusMode("Pending");
        tr.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
         TechnicianReports tr= new TechnicianReports();
        tr.setStatusMode("Completed");
        tr.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
         TechnicianReports tr= new TechnicianReports();
        tr.setStatusMode("Failed");
        tr.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
         TechnicianReports tr= new TechnicianReports();
        tr.setStatusMode("Delivered");
        tr.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        StatusReport sr = new StatusReport();
        sr.loadTable("cdelivery");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
          SuccessReport sr = new SuccessReport();

          sr.setVisible(true);
          
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
         TechnicianReports tr= new TechnicianReports();
        tr.setStatusMode("dlist");
        tr.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        DailyReport d = new DailyReport();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem NewComplaint;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JMenuItem SearchMenu;
    private javax.swing.JMenu adminMenu;
    private javax.swing.JMenuItem changePasswd;
    private javax.swing.JMenuItem delHandset;
    private javax.swing.JMenu deliveryMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newSetsMenu;
    private javax.swing.JButton newbTN;
    private javax.swing.JButton printBtn;
    private javax.swing.JMenuItem printMenu;
    private javax.swing.JMenu profileMenu;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton statbttn;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JMenu statusMenu;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JMenu techReportsMenu;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
    private static String ServiceID=null;
    

    public static void setServiceID(String id)
{
    ServiceID=id;
}
}
