/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewReport.java
 *
 * Created on Aug 28, 2015, 3:22:57 PM
 */

package serviceportal;

import java.awt.Font;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.imageio.ImageIO;

/**
 *
 * @author sonytara
 */
public class ViewReport extends javax.swing.JFrame {

    /** Creates new form ViewReport */
    public ViewReport() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jXImageView1 = new org.jdesktop.swingx.JXImageView();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cnameLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contactLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modelLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        complaintLbl1 = new javax.swing.JLabel();
        accrLbl = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        amountLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        recvdbyLbl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        techLbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        recvdDateLbl = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        remarksLbl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        imeiLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        advancelbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        balancelbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        serviceidLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        secondcomplaint = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        extracosts = new javax.swing.JLabel();
        deliveryLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(serviceportal.ServicePortalApp.class).getContext().getResourceMap(ViewReport.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        jXImageView1.setName("jXImageView1"); // NOI18N
        jXImageView1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXImageView1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jXImageView1Layout = new javax.swing.GroupLayout(jXImageView1);
        jXImageView1.setLayout(jXImageView1Layout);
        jXImageView1Layout.setHorizontalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );
        jXImageView1Layout.setVerticalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXImageView1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXImageView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(770, 11, 380, 400);

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cnameLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        cnameLbl.setText(resourceMap.getString("cnameLbl.text")); // NOI18N
        cnameLbl.setName("cnameLbl"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        contactLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        contactLbl.setText(resourceMap.getString("contactLbl.text")); // NOI18N
        contactLbl.setName("contactLbl"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        modelLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        modelLbl.setText(resourceMap.getString("modelLbl.text")); // NOI18N
        modelLbl.setName("modelLbl"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        complaintLbl1.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        complaintLbl1.setText(resourceMap.getString("complaintLbl1.text")); // NOI18N
        complaintLbl1.setName("complaintLbl1"); // NOI18N

        accrLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        accrLbl.setText(resourceMap.getString("accrLbl.text")); // NOI18N
        accrLbl.setName("accrLbl"); // NOI18N

        statusLbl.setBackground(resourceMap.getColor("statusLbl.background")); // NOI18N
        statusLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        statusLbl.setText(resourceMap.getString("statusLbl.text")); // NOI18N
        statusLbl.setName("statusLbl"); // NOI18N

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        amountLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        amountLbl.setText(resourceMap.getString("amountLbl.text")); // NOI18N
        amountLbl.setName("amountLbl"); // NOI18N

        jLabel11.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        recvdbyLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        recvdbyLbl.setText(resourceMap.getString("recvdbyLbl.text")); // NOI18N
        recvdbyLbl.setName("recvdbyLbl"); // NOI18N

        jLabel13.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        techLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        techLbl.setText(resourceMap.getString("techLbl.text")); // NOI18N
        techLbl.setName("techLbl"); // NOI18N

        jLabel15.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        recvdDateLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        recvdDateLbl.setForeground(resourceMap.getColor("recvdDateLbl.foreground")); // NOI18N
        recvdDateLbl.setText(resourceMap.getString("recvdDateLbl.text")); // NOI18N
        recvdDateLbl.setName("recvdDateLbl"); // NOI18N

        jLabel17.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        timeLbl.setBackground(resourceMap.getColor("timeLbl.background")); // NOI18N
        timeLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        timeLbl.setForeground(resourceMap.getColor("recvdDateLbl.foreground")); // NOI18N
        timeLbl.setText(resourceMap.getString("timeLbl.text")); // NOI18N
        timeLbl.setName("timeLbl"); // NOI18N

        remarksLbl.setBackground(resourceMap.getColor("remarksLbl.background")); // NOI18N
        remarksLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        remarksLbl.setText(resourceMap.getString("remarksLbl.text")); // NOI18N
        remarksLbl.setName("remarksLbl"); // NOI18N

        jLabel20.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel21.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel18.setFont(resourceMap.getFont("jLabel18.font")); // NOI18N
        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        imeiLbl.setFont(resourceMap.getFont("imeiLbl.font")); // NOI18N
        imeiLbl.setText(resourceMap.getString("imeiLbl.text")); // NOI18N
        imeiLbl.setName("imeiLbl"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        advancelbl.setText(resourceMap.getString("advancelbl.text")); // NOI18N
        advancelbl.setName("advancelbl"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        balancelbl.setText(resourceMap.getString("balancelbl.text")); // NOI18N
        balancelbl.setName("balancelbl"); // NOI18N

        jPanel3.setBackground(resourceMap.getColor("jPanel3.background")); // NOI18N
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, resourceMap.getColor("jPanel3.border.matteColor"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        serviceidLbl.setFont(resourceMap.getFont("accrLbl.font")); // NOI18N
        serviceidLbl.setForeground(resourceMap.getColor("serviceidLbl.foreground")); // NOI18N
        serviceidLbl.setText(resourceMap.getString("serviceidLbl.text")); // NOI18N
        serviceidLbl.setName("serviceidLbl"); // NOI18N
        Font f = new Font(Font.DIALOG,Font.BOLD,16);
        serviceidLbl.setFont(f);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(serviceidLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(serviceidLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        secondcomplaint.setFont(resourceMap.getFont("secondcomplaint.font")); // NOI18N
        secondcomplaint.setText(resourceMap.getString("secondcomplaint.text")); // NOI18N
        secondcomplaint.setName("secondcomplaint"); // NOI18N

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        extracosts.setText(resourceMap.getString("extracosts.text")); // NOI18N
        extracosts.setName("extracosts"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(secondcomplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(accrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(amountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(remarksLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(recvdDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(recvdbyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(techLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(imeiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(complaintLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(advancelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extracosts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balancelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {advancelbl, balancelbl, extracosts});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(advancelbl))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(extracosts))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(modelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(complaintLbl1)))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(secondcomplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(statusLbl)))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(remarksLbl)))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(recvdDateLbl))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(timeLbl)))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(recvdbyLbl)))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(techLbl)))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(imeiLbl))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(balancelbl)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cnameLbl)
                        .addGap(11, 11, 11)
                        .addComponent(contactLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {balancelbl, jLabel6});

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 10, 700, 540);

        deliveryLbl.setFont(resourceMap.getFont("deliveryLbl.font")); // NOI18N
        deliveryLbl.setForeground(resourceMap.getColor("deliveryLbl.foreground")); // NOI18N
        deliveryLbl.setText(resourceMap.getString("deliveryLbl.text")); // NOI18N
        deliveryLbl.setName("deliveryLbl"); // NOI18N
        getContentPane().add(deliveryLbl);
        deliveryLbl.setBounds(780, 430, 400, 40);

        dateLbl.setFont(resourceMap.getFont("dateLbl.font")); // NOI18N
        dateLbl.setForeground(resourceMap.getColor("dateLbl.foreground")); // NOI18N
        dateLbl.setText(resourceMap.getString("dateLbl.text")); // NOI18N
        dateLbl.setName("dateLbl"); // NOI18N
        getContentPane().add(dateLbl);
        dateLbl.setBounds(780, 490, 250, 20);
        dateLbl.setVisible(false);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1200)/2, (screenSize.height-600)/2, 1200, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jXImageView1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXImageView1MouseClicked
        // TODO add your handling code here:

        try
        {
            File file  = new File("images/"+fileName);
            Image img = ImageIO.read(file);

            ImageViewer imv = new ImageViewer();
            imv.setImage(img);
            imv.setSize(img.getWidth(imv),img.getHeight(imv));
            imv.setVisible(true);


        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jXImageView1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accrLbl;
    private javax.swing.JLabel advancelbl;
    private javax.swing.JLabel amountLbl;
    private javax.swing.JLabel balancelbl;
    private javax.swing.JLabel cnameLbl;
    private javax.swing.JLabel complaintLbl1;
    private javax.swing.JLabel contactLbl;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel deliveryLbl;
    private javax.swing.JLabel extracosts;
    private javax.swing.JLabel imeiLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private org.jdesktop.swingx.JXImageView jXImageView1;
    private javax.swing.JLabel modelLbl;
    private javax.swing.JLabel recvdDateLbl;
    private javax.swing.JLabel recvdbyLbl;
    private javax.swing.JLabel remarksLbl;
    private javax.swing.JLabel secondcomplaint;
    private javax.swing.JLabel serviceidLbl;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JLabel techLbl;
    private javax.swing.JLabel timeLbl;
    // End of variables declaration//GEN-END:variables

    private static final int IMG_WIDTH = 398;
    private static final int IMG_HEIGHT = 398;
    private static String fileName="";

    public void setDetails(String serviceID) {
       Connection con = null;
       Statement st = null;
       ResultSet rs = null;
       fileName="";
       try
       {
           DateFormat df = new SimpleDateFormat("dd-MMM-yy");
           con = DBConnection.getConnection();
           st=con.createStatement();
           rs=st.executeQuery("select * from complaint where receipt_no like '%"+serviceID+"%'");
           while(rs.next())
           {
             fileName=rs.getString("image_names");
             cnameLbl.setText(rs.getString("cname"));
             contactLbl.setText(rs.getString("contact_no"));
             modelLbl.setText(rs.getString("phone_model"));
             complaintLbl1.setText(rs.getString("complaint_name"));
             accrLbl.setText(rs.getString("recvd_accr"));
             recvdbyLbl.setText(rs.getString("recvd_by"));
             serviceidLbl.setText(rs.getString("receipt_no"));
             imeiLbl.setText(rs.getString("imei_no"));
             amountLbl.setText(rs.getString("est_chargs"));
             techLbl.setText(rs.getString("assigned_to"));
             recvdDateLbl.setText(df.format(rs.getDate("recvd_date")));
             timeLbl.setText(rs.getString("recvd_time"));
             advancelbl.setText(rs.getString("advance"));
             balancelbl.setText(rs.getString("balance"));
             extracosts.setText(new AddCharges().getCharges(serviceID)+"");
             secondcomplaint.setText(new AddCharges().getComplaint(serviceID));
           }
           File img  = new File("images/"+fileName);
           if(img.exists())
           {
            try{

		BufferedImage originalImage = ImageIO.read(img);
		int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
		BufferedImage resizeImageHint = resizeImageWithHint(originalImage, type);
                jXImageView1.setImage(resizeImageHint);


	     }
            catch(IOException e){
		System.out.println(e.getMessage());
	  }



           }
           
           rs=st.executeQuery("select * from status where receipt_no='"+serviceID+"'");
           String delivery="";
           while(rs.next())
           {
               statusLbl.setText(rs.getString("status"));
               remarksLbl.setText(rs.getString("remarks"));
               delivery=rs.getString("delivery_status");

           }
           

           if(delivery.equals("Delivered"))
           {
               rs=st.executeQuery("select * from delivery where receipt_no='"+serviceID+"'");
           Date delDate=null;
           String time="";
           while(rs.next())
           {
               delDate=rs.getDate("delivery_date");
               time=rs.getString("delivery_time");
           }
          
              DateFormat df1= new SimpleDateFormat("dd-MMM-yy");
              Date d1 = new Date();
              Integer days = (int)(d1.getTime()-delDate.getTime())/(1000*60*60*24);
              String daystring="";
              if(days<1)
              {
                  daystring="ToDay";
              }
              else
                  daystring=days.toString()+" days ago";
               deliveryLbl.setText("This Handset has been delivered "+daystring);
               dateLbl.setText("On Date: "+df1.format(delDate)+" "+time);
               dateLbl.setVisible(true);
           }
               
           else
               deliveryLbl.setVisible(false);
           

       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
    }

    private static BufferedImage resizeImageWithHint(BufferedImage originalImage, int type){

	BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
	Graphics2D g = resizedImage.createGraphics();
	g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
	g.dispose();
	g.setComposite(AlphaComposite.Src);

	g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
	RenderingHints.VALUE_INTERPOLATION_BILINEAR);
	g.setRenderingHint(RenderingHints.KEY_RENDERING,
	RenderingHints.VALUE_RENDER_QUALITY);
	g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
	RenderingHints.VALUE_ANTIALIAS_ON);

	return resizedImage;
    }

}
