--------------------------------------------------------
--  File created - Saturday-June-19-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BILLPART
--------------------------------------------------------

  CREATE TABLE "DIGITAL"."BILLPART" 
   (	"LAST" VARCHAR2(20 BYTE), 
	"DAYS_NO" VARCHAR2(20 BYTE), 
	"EX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CANCELLED
--------------------------------------------------------

  CREATE TABLE "DIGITAL"."CANCELLED" 
   (	"RECEIPT_NO" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CANCELLED_DATE" DATE, 
	"CANCELLED_TIME" VARCHAR2(20 BYTE), 
	"CANCELLED_BY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIST
--------------------------------------------------------

  CREATE TABLE "DIGITAL"."CLIST" 
   (	"COMPLAINT_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPLAINT
--------------------------------------------------------

  CREATE TABLE "DIGITAL"."COMPLAINT" 
   (	"CNAME" VARCHAR2(20 BYTE), 
	"CONTACT_NO" NUMBER(10,0), 
	"PHONE_MODEL" VARCHAR2(20 BYTE), 
	"COMPLAINT_NAME" VARCHAR2(20 BYTE), 
	"RECVD_ACCR" VARCHAR2(200 BYTE), 
	"RECVD_BY" VARCHAR2(20 BYTE), 
	"RECEIPT_NO" VARCHAR2(20 BYTE), 
	"RECVD_DATE" DATE, 
	"EST_CHARGS" NUMBER(9,0), 
	"RECVD_TIME" VARCHAR2(20 BYTE), 
	"IMEI_NO" NUMBER(15,0), 
	"ASSIGNED_TO" VARCHAR2(20 BYTE), 
	"IMAGE_NAMES" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"ADVANCE" NUMBER DEFAULT 0, 
	"BALANCE" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DELIVERY
--------------------------------------------------------

  CREATE TABLE "DIGITAL"."DELIVERY" 
   (	"RECEIPT_NO" VARCHAR2(20 BYTE), 
	"DELIVERY_DATE" DATE, 
	"AMOUNT" NUMBER(9,0), 
	"ISSUED_BY" VARCHAR2(20 BYTE), 
	"DELIVERY_TIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYMENTS
--------------------------------------------------------

  CREATE TABLE "DIGITAL"."PAYMENTS" 
   (	"SERVICEID" VARCHAR2(20 BYTE), 
	"RECEIVED_AMOUNT" NUMBER(8,0), 
	"TYPE" VARCHAR2(20 BYTE), 
	"RECEIVED_DATE" DATE, 
	"RECIEVED_TIME" VARCHAR2(20 BYTE), 
	"RECEIVED_BY" VARCHAR2(20 BYTE), 
	"CASHMODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATUS
--------------------------------------------------------

  CREATE TABLE "DIGITAL"."STATUS" 
   (	"RECEIPT_NO" VARCHAR2(20 BYTE), 
	"REMARKS" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"STATUS_DATE" DATE, 
	"DELIVERY_STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TECHNICIAN
--------------------------------------------------------

  CREATE TABLE "DIGITAL"."TECHNICIAN" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"PASSWD" VARCHAR2(20 BYTE), 
	"FULL_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "DIGITAL"."USERS" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"PASSWD" VARCHAR2(20 BYTE), 
	"USER_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DIGITAL.BILLPART
SET DEFINE OFF;
Insert into DIGITAL.BILLPART (LAST,DAYS_NO,EX) values ('4','170','PASS');
REM INSERTING into DIGITAL.CANCELLED
SET DEFINE OFF;
REM INSERTING into DIGITAL.CLIST
SET DEFINE OFF;
Insert into DIGITAL.CLIST (COMPLAINT_NAME) values ('Display Problem');
REM INSERTING into DIGITAL.COMPLAINT
SET DEFINE OFF;
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('szxvgsd',null,'sadfas','Display Problem','Phone','admin','21161004',to_date('10-JUN-21','DD-MON-RR'),1500,'22:05',null,null,null,null,600,900);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('dxvbsd',null,'sfaswf','Display Problem','Phone','admin','21161005',to_date('10-JUN-21','DD-MON-RR'),600,'22:11',null,null,null,null,100,500);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('vjhfj',null,'nbvbhnj','Display Problem','Phone','admin','21161006',to_date('10-JUN-21','DD-MON-RR'),900,'22:15',null,null,null,null,100,800);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('dg',null,'sfawsf','Display Problem','Phone','admin','21161007',to_date('10-JUN-21','DD-MON-RR'),700,'22:21',null,null,null,null,150,550);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('xdzvgsd',null,'svfsav','Display Problem','Phone','admin','21161008',to_date('10-JUN-21','DD-MON-RR'),300,'22:23',null,null,null,null,100,200);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('dgsdg',null,'dgds','Display Problem','Phone','admin','21162001',to_date('11-JUN-21','DD-MON-RR'),5000,'00:56',null,null,null,null,2500,2500);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('dbgdsg',null,'nbvjbk','Display Problem','Phone','admin','21161002',to_date('10-JUN-21','DD-MON-RR'),2000,'21:49',null,null,null,null,500,1500);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('asfasf',null,'safsaf','Display Problem','Phone','admin','21161003',to_date('10-JUN-21','DD-MON-RR'),1000,'21:49',null,null,null,null,100,900);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('eyery',9963695064,'fgjfgj','Display Problem','Phone','admin','21165001',to_date('14-JUN-21','DD-MON-RR'),0,'22:51',null,'user1',null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('eyery',9963695064,'fgjfgj','Display Problem','Phone','admin','21165001',to_date('14-JUN-21','DD-MON-RR'),0,'22:53',null,'user1',null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('eyery',9963695064,'fgjfgj','Display Problem','Phone','admin','21165001',to_date('14-JUN-21','DD-MON-RR'),0,'22:54',null,'user1',null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('egweg',9963695064,'dfghdfh','Display Problem','Phone','admin','21165002',to_date('14-JUN-21','DD-MON-RR'),0,'23:00',null,null,null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('egsrgdg',9963695064,'fhdfh','Display Problem','Phone','admin','21165003',to_date('14-JUN-21','DD-MON-RR'),0,'23:02',null,null,null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('fufguj',9963695064,'nbchg','Display Problem','Phone','admin','21165004',to_date('14-JUN-21','DD-MON-RR'),0,'23:05',null,null,null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('bxcn',null,'gmgm','Display Problem','Phone','admin','21166001',to_date('15-JUN-21','DD-MON-RR'),0,'19:35',null,null,null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('gmgfj',null,'ghjgfj','Display Problem','Phone','admin','21166001',to_date('15-JUN-21','DD-MON-RR'),0,'19:43',null,null,null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('sgdrh',null,'hfgjh','Display Problem','Phone','admin','21166001',to_date('15-JUN-21','DD-MON-RR'),0,'19:50',null,null,null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('hmh',null,'hkhgk','Display Problem','Phone','admin','21166001',to_date('15-JUN-21','DD-MON-RR'),0,'19:51',null,null,null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('gjghjgh',null,'ghjkghkj','Display Problem','Phone','admin','21166001',to_date('15-JUN-21','DD-MON-RR'),0,'19:52',null,null,null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('fgjjg',null,'hgkhgk','Display Problem','Phone','admin','21166002',to_date('15-JUN-21','DD-MON-RR'),0,'19:53',null,null,null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('dsgsdg',null,'fdhdfh','Display Problem','Phone','admin','21168001',to_date('17-JUN-21','DD-MON-RR'),2000,'21:04',null,null,null,null,500,1500);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('fdhdfjh',null,'fdhdfh','Display Problem','Phone','admin','21168002',to_date('17-JUN-21','DD-MON-RR'),2000,'22:13',null,null,null,null,1000,1000);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('raj',null,'vivo','Display Problem','Phone','admin','21168003',to_date('17-JUN-21','DD-MON-RR'),7000,'22:53',null,null,null,null,2000,5000);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('naj',null,'oppo','Display Problem','Phone','admin','21168004',to_date('17-JUN-21','DD-MON-RR'),3000,'22:54',null,null,null,null,500,2500);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('sam',null,'mol','Display Problem','Phone','admin','21168005',to_date('17-JUN-21','DD-MON-RR'),2200,'22:59',null,null,null,null,200,2000);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('HGJH',null,'GHHFHF','Display Problem','Phone','admin','21168006',to_date('17-JUN-21','DD-MON-RR'),2000,'23:19',null,null,null,null,600,1400);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('CNCV',null,'BJ','Display Problem','Phone','admin','21168007',to_date('17-JUN-21','DD-MON-RR'),1000,'23:22',null,null,null,null,150,850);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('VCGH',null,'HGVJK','Display Problem','Phone','admin','21168008',to_date('17-JUN-21','DD-MON-RR'),5000,'23:25',null,null,null,null,2000,3000);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('dfhdfh',null,'fgjfgj','Display Problem','Phone','admin','21169001',to_date('18-JUN-21','DD-MON-RR'),2000,'00:01',null,null,null,null,150,1850);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('dghdfhfddfh',null,'fdhdfh','Display Problem','Phone','admin','21166004',to_date('15-JUN-21','DD-MON-RR'),2000,'20:26',null,null,null,null,500,1500);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('hfghfgh',null,'fdhfghfg','Display Problem','Phone','admin','21166005',to_date('15-JUN-21','DD-MON-RR'),5000,'20:26',null,null,null,null,1200,3800);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('gsghsdfgh',null,'fgjfxgjfgj','Display Problem','Phone','admin','21167001',to_date('16-JUN-21','DD-MON-RR'),2000,'21:24',null,null,null,null,100,1900);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('ghhyhj',null,'gjgjh','Display Problem','Phone','admin','21167002',to_date('16-JUN-21','DD-MON-RR'),2000,'22:16',null,null,null,null,500,1500);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('jhgjhvk',null,'jhgjg','Display Problem','Phone','admin','21167003',to_date('16-JUN-21','DD-MON-RR'),2000,'22:19',null,null,null,null,500,1500);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('fvncv',null,'vcncvn','Display Problem','Phone','admin','21169002',to_date('18-JUN-21','DD-MON-RR'),0,'20:21',null,'user1',null,null,0,0);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('dfdfhdf',null,'dfhdfjh','Display Problem','Phone','admin','21170001',to_date('19-JUN-21','DD-MON-RR'),2000,'00:39',null,null,null,null,500,1500);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('dfhbd',null,'fhfgjn','Display Problem','Phone','admin','21170002',to_date('19-JUN-21','DD-MON-RR'),2000,'01:19',null,null,null,null,500,1500);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('cvnvbm',null,'gfjmgfm','Display Problem','Phone','user1','21170003',to_date('19-JUN-21','DD-MON-RR'),2500,'01:23',null,null,null,null,600,1900);
Insert into DIGITAL.COMPLAINT (CNAME,CONTACT_NO,PHONE_MODEL,COMPLAINT_NAME,RECVD_ACCR,RECVD_BY,RECEIPT_NO,RECVD_DATE,EST_CHARGS,RECVD_TIME,IMEI_NO,ASSIGNED_TO,IMAGE_NAMES,EMAIL,ADVANCE,BALANCE) values ('vbhkhgk',null,'hgkghk','Display Problem','Phone','user1','21170004',to_date('19-JUN-21','DD-MON-RR'),2100,'01:24',null,null,null,null,1000,1100);
REM INSERTING into DIGITAL.DELIVERY
SET DEFINE OFF;
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21161005',to_date('10-JUN-21','DD-MON-RR'),600,'admin','22:11');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21161006',to_date('10-JUN-21','DD-MON-RR'),900,'admin','22:15');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21161003',to_date('10-JUN-21','DD-MON-RR'),1000,'admin','21:58');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21161004',to_date('10-JUN-21','DD-MON-RR'),1500,'admin','22:06');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21161007',to_date('10-JUN-21','DD-MON-RR'),700,'admin','22:22');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21161008',to_date('10-JUN-21','DD-MON-RR'),300,'admin','22:23');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21162001',to_date('11-JUN-21','DD-MON-RR'),5000,'admin','00:57');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21165002',to_date('15-JUN-21','DD-MON-RR'),0,'admin','19:29');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21165004',to_date('15-JUN-21','DD-MON-RR'),0,'admin','19:31');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21166001',to_date('15-JUN-21','DD-MON-RR'),0,'admin','19:36');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21166001',to_date('15-JUN-21','DD-MON-RR'),0,'admin','19:48');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21165003',to_date('15-JUN-21','DD-MON-RR'),0,'admin','19:49');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21166001',to_date('15-JUN-21','DD-MON-RR'),0,'admin','19:50');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21166001',to_date('15-JUN-21','DD-MON-RR'),0,'admin','19:51');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21166001',to_date('15-JUN-21','DD-MON-RR'),0,'admin','19:58');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21166002',to_date('15-JUN-21','DD-MON-RR'),0,'admin','19:58');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21168004',to_date('17-JUN-21','DD-MON-RR'),3000,'admin','23:04');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21167001',to_date('16-JUN-21','DD-MON-RR'),2000,'admin','21:25');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21168002',to_date('17-JUN-21','DD-MON-RR'),2000,'admin','23:06');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21167002',to_date('16-JUN-21','DD-MON-RR'),2000,'admin','22:17');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21167003',to_date('17-JUN-21','DD-MON-RR'),2000,'admin','22:34');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21168008',to_date('17-JUN-21','DD-MON-RR'),5000,'admin','23:25');
Insert into DIGITAL.DELIVERY (RECEIPT_NO,DELIVERY_DATE,AMOUNT,ISSUED_BY,DELIVERY_TIME) values ('21169001',to_date('18-JUN-21','DD-MON-RR'),2000,'admin','00:20');
REM INSERTING into DIGITAL.PAYMENTS
SET DEFINE OFF;
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161003',900,'Balance Amount',to_date('10-JUN-21','DD-MON-RR'),'21:58','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161002',500,'advance',to_date('10-JUN-21','DD-MON-RR'),'21:49','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161003',100,'advance',to_date('10-JUN-21','DD-MON-RR'),'21:49','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161004',600,'advance',to_date('10-JUN-21','DD-MON-RR'),'22:05','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161004',900,'Balance Amount',to_date('10-JUN-21','DD-MON-RR'),'22:06','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161005',100,'advance',to_date('10-JUN-21','DD-MON-RR'),'22:11','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161005',500,'Balance Amount',to_date('10-JUN-21','DD-MON-RR'),'22:11','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161006',100,'advance',to_date('10-JUN-21','DD-MON-RR'),'22:15','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161006',800,'Balance Amount',to_date('10-JUN-21','DD-MON-RR'),'22:15','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161007',150,'advance',to_date('10-JUN-21','DD-MON-RR'),'22:21','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161007',550,'Balance Amount',to_date('10-JUN-21','DD-MON-RR'),'22:22','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161008',100,'advance',to_date('10-JUN-21','DD-MON-RR'),'22:23','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21161008',200,'Balance Amount',to_date('10-JUN-21','DD-MON-RR'),'22:23','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21162001',2500,'advance',to_date('11-JUN-21','DD-MON-RR'),'00:56','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21162001',2500,'Balance Amount',to_date('11-JUN-21','DD-MON-RR'),'00:57','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165001',500,'advance',to_date('14-JUN-21','DD-MON-RR'),'22:51','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165001',500,'advance',to_date('14-JUN-21','DD-MON-RR'),'22:53','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165001',500,'advance',to_date('14-JUN-21','DD-MON-RR'),'22:54','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165002',100,'advance',to_date('14-JUN-21','DD-MON-RR'),'23:00','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165003',700,'advance',to_date('14-JUN-21','DD-MON-RR'),'23:02','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165004',100,'advance',to_date('14-JUN-21','DD-MON-RR'),'23:05','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165002',0,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:29','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165002',0,'Balance Amount',to_date('15-JUN-21','DD-MON-RR'),'19:29','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165003',0,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:31','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165004',-100,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:31','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165004',0,'Balance Amount',to_date('15-JUN-21','DD-MON-RR'),'19:31','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166001',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:35','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166001',-100,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:36','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166001',0,'Balance Amount',to_date('15-JUN-21','DD-MON-RR'),'19:36','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21165001',0,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:37','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166001',400,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:43','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166001',0,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:43','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166001',50,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:50','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166001',0,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:50','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166001',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:51','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166001',0,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:51','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166001',400,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:52','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166002',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:53','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166001',0,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:58','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166002',-100,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:58','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166003',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:59','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166003',-100,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:59','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166003',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'19:59','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166003',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'20:00','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166003',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'20:11','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166003',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'20:16','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166003',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'20:16','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166003',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'20:18','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166003',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'20:19','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166003',100,'advance',to_date('15-JUN-21','DD-MON-RR'),'20:26','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166004',500,'advance',to_date('15-JUN-21','DD-MON-RR'),'20:26','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166005',1200,'advance',to_date('15-JUN-21','DD-MON-RR'),'20:26','admin',null);
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21167001',100,'advance',to_date('16-JUN-21','DD-MON-RR'),'21:24','admin','UPI');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21167001',1900,'Balance Amount',to_date('16-JUN-21','DD-MON-RR'),'21:25','admin','UPI');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21166003',1900,'Balance Amount',to_date('16-JUN-21','DD-MON-RR'),'21:27','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21167002',500,'advance',to_date('16-JUN-21','DD-MON-RR'),'22:16','admin','UPI');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21167002',1500,'Balance Amount',to_date('16-JUN-21','DD-MON-RR'),'22:17','admin','UPI');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21167003',500,'advance',to_date('16-JUN-21','DD-MON-RR'),'22:19','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21168001',500,'advance',to_date('17-JUN-21','DD-MON-RR'),'21:04','admin','UPI');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21168002',1000,'advance',to_date('17-JUN-21','DD-MON-RR'),'22:13','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21167003',1500,'Balance Amount',to_date('17-JUN-21','DD-MON-RR'),'22:34','admin','UPI');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21168003',2000,'advance',to_date('17-JUN-21','DD-MON-RR'),'22:53','admin','UPI');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21168004',500,'advance',to_date('17-JUN-21','DD-MON-RR'),'22:54','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21168005',200,'advance',to_date('17-JUN-21','DD-MON-RR'),'22:59','admin','UPI');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21168004',2500,'Balance Amount',to_date('17-JUN-21','DD-MON-RR'),'23:04','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21168002',1000,'Balance Amount',to_date('17-JUN-21','DD-MON-RR'),'23:06','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21168006',600,'advance',to_date('17-JUN-21','DD-MON-RR'),'23:19','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21168007',150,'advance',to_date('17-JUN-21','DD-MON-RR'),'23:22','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21168008',2000,'advance',to_date('17-JUN-21','DD-MON-RR'),'23:25','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21168008',3000,'Balance Amount',to_date('17-JUN-21','DD-MON-RR'),'23:25','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21169001',150,'advance',to_date('18-JUN-21','DD-MON-RR'),'00:01','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21169001',1850,'Balance Amount',to_date('18-JUN-21','DD-MON-RR'),'00:20','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21169002',200,'advance',to_date('18-JUN-21','DD-MON-RR'),'20:30','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21169002',0,'advance',to_date('18-JUN-21','DD-MON-RR'),'22:44','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21170001',500,'advance',to_date('19-JUN-21','DD-MON-RR'),'00:39','admin','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21170002',500,'advance',to_date('19-JUN-21','DD-MON-RR'),'01:19','admin','UPI');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21170003',600,'advance',to_date('19-JUN-21','DD-MON-RR'),'01:23','user1','Direct Cash');
Insert into DIGITAL.PAYMENTS (SERVICEID,RECEIVED_AMOUNT,TYPE,RECEIVED_DATE,RECIEVED_TIME,RECEIVED_BY,CASHMODE) values ('21170004',1000,'advance',to_date('19-JUN-21','DD-MON-RR'),'01:24','user1','UPI');
REM INSERTING into DIGITAL.STATUS
SET DEFINE OFF;
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21161004','xzcv','Completed',to_date('10-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21161005','sadgsd','Completed',to_date('10-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21161006','xzvzx','Completed',to_date('10-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21161007','zsag','Completed',to_date('10-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21161008','z','Completed',to_date('10-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21162001','sc','Completed',to_date('11-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21161002','szxvfsa','Completed',to_date('10-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21161003','cxb','Completed',to_date('10-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21165001','32','Pending',to_date('16-JUN-21','DD-MON-RR'),'NO');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21165001','32','Pending',to_date('16-JUN-21','DD-MON-RR'),'NO');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21165001','32','Pending',to_date('16-JUN-21','DD-MON-RR'),'NO');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21165002','trj','Failed',to_date('15-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21165003','tj','Failed',to_date('15-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21165004','tuj','Failed',to_date('15-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21166001','gmn','Failed',to_date('15-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21166001','gmn','Failed',to_date('15-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21166001','gmn','Failed',to_date('15-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21166001','gmn','Failed',to_date('15-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21166001','gmn','Failed',to_date('15-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21166002','gjn','Failed',to_date('15-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21168001','MM','Completed',to_date('17-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21168002','ok','Completed',to_date('17-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21168003','ok','Completed',to_date('17-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21168004','FVH','Completed',to_date('17-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21168005','ok','Completed',to_date('17-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21168006','VJHN','Completed',to_date('17-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21168007','KJ','Completed',to_date('17-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21168008','BJ','Completed',to_date('17-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21169001','af','Completed',to_date('18-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21166004','jkbkj','Completed',to_date('16-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21166005','u','Completed',to_date('16-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21167001','vgmg','Completed',to_date('16-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21167002','k;lkm','Completed',to_date('16-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21167003','HJK','Completed',to_date('17-JUN-21','DD-MON-RR'),'Delivered');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21169002','gh','Failed',to_date('18-JUN-21','DD-MON-RR'),'NO');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21170001','Display Problem','New',to_date('19-JUN-21','DD-MON-RR'),'NO');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21170002','Display Problem','New',to_date('19-JUN-21','DD-MON-RR'),'NO');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21170003','Display Problem','New',to_date('19-JUN-21','DD-MON-RR'),'NO');
Insert into DIGITAL.STATUS (RECEIPT_NO,REMARKS,STATUS,STATUS_DATE,DELIVERY_STATUS) values ('21170004','Display Problem','New',to_date('19-JUN-21','DD-MON-RR'),'NO');
REM INSERTING into DIGITAL.TECHNICIAN
SET DEFINE OFF;
Insert into DIGITAL.TECHNICIAN (USERID,PASSWD,FULL_NAME) values ('user1','1234','ravi');
REM INSERTING into DIGITAL.USERS
SET DEFINE OFF;
Insert into DIGITAL.USERS (USERID,PASSWD,USER_TYPE) values ('admin','ADMIN567','ADMIN');
